runtime: nodejs16

instance_class: F2

env_variables: 
  BUCKET_NAME: "samuelesquercastro"

handlers:
- url: /
  static_files: dist/my-portfolio/index.html
  upload: dist/my-portfolio/index.html

- url: /
  static_dir: dist/my-portfolio 